behaviors:
  SkeletonAgent: # Must match Behavior Name in Unity
    trainer_type: ppo # Or sac
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true # Good for continuous observations
      hidden_units: 128 # Number of units in hidden layers
      num_layers: 2    # Number of hidden layers
      vis_encode_type: simple # If you add visual observations
    reward_signals:
      extrinsic:
        gamma: 0.99 # Discount factor
        strength: 1.0
    max_steps: 500000  # Total steps for training
    time_horizon: 64
    summary_freq: 10000

